const select=document.getElementById('store'),status=document.getElementById('status'),form=document.getElementById('productForm');
select.value=['academia','construcao'].includes(new URLSearchParams(location.search).get('loja'))?new URLSearchParams(location.search).get('loja'):'academia';
let loja,items=[],editing=null;
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){loja=HorizonHub.store(select.value);document.getElementById('backStore').href='/lojas/'+select.value+'/';editing=null;form.reset();document.getElementById('manage').hidden=true;document.getElementById('login').hidden=!!HorizonHub.session();if(!HorizonHub.session())return;status.textContent='Conferindo acesso…';try{items=await loja.adminProducts();document.getElementById('manage').hidden=false;status.textContent='Você administra esta loja.';document.getElementById('products').innerHTML=items.map(p=>`<div class="cart-row"><span>${escapeHTML(p.nome)} · ${Number(p.preco).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} · ${Number(p.estoque)} un.</span><button data-edit="${escapeHTML(p.id)}">Editar</button></div>`).join('')||'<p>Nenhum produto cadastrado.</p>';}catch(e){status.textContent=e.message;document.getElementById('login').hidden=false;}}
select.addEventListener('change',load);
document.getElementById('login').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const values=new FormData(e.target);await HorizonHub.login(values.get('email').trim(),values.get('password'));await load();}catch(err){status.textContent=err.message;}finally{button.disabled=false;}});
document.getElementById('logout').addEventListener('click',async()=>{await HorizonHub.logout();load();});
document.getElementById('new').addEventListener('click',()=>{editing=null;form.reset();});
document.getElementById('products').addEventListener('click',e=>{const button=e.target.closest('[data-edit]');if(!button)return;const product=items.find(p=>p.id===button.dataset.edit);if(!product)return;editing=product.id;for(const name of ['nome','slug','descricao','preco','imagem_url','estoque','ativo'])form.elements[name].value=String(product[name]??'');form.scrollIntoView({behavior:'smooth'});});
form.addEventListener('submit',async e=>{e.preventDefault();const button=document.getElementById('save');button.disabled=true;const data=Object.fromEntries(new FormData(form));data.preco=Number(data.preco);data.estoque=Number(data.estoque);data.ativo=data.ativo==='true';if(data.imagem_url&&!data.imagem_url.startsWith('https://')&&!data.imagem_url.startsWith('/'))data.imagem_url='/lojas/'+select.value+'/'+data.imagem_url.replace(/^\.\//,'');try{await loja.saveProduct(data,editing);await load();status.textContent='Produto salvo.';}catch(err){status.textContent=err.message;}finally{button.disabled=false;}});
load();
