const slug=document.querySelector('meta[name="loja"]').content,loja=HorizonHub.store(slug);
document.body.classList.add(slug);const catalog=document.getElementById('catalog'),result=document.getElementById('result');
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function imageURL(v){try{const u=new URL(v,location.origin);return v&&['https:','http:'].includes(u.protocol)?escapeHTML(u.href):'';}catch{return '';}}
let products=[];
async function renderCart(){const items=loja.cart();document.getElementById('checkout').disabled=!items.length;document.getElementById('cart').innerHTML=items.length?items.map(i=>`<div class="cart-row"><span>${escapeHTML(products.find(p=>p.id===i.product_id)?.nome||'Produto')} · ${i.quantity} un.</span><button data-remove="${escapeHTML(i.product_id)}">Remover</button></div>`).join(''):'<p class="quiet">Escolha uma opção para começar.</p>';}
async function load(){try{products=await loja.products();catalog.innerHTML=products.length?products.map(p=>`<article class="product">${imageURL(p.imagem_url)?`<img src="${imageURL(p.imagem_url)}" alt="${escapeHTML(p.nome)}" loading="lazy">`:''}<h3>${escapeHTML(p.nome)}</h3><p>${escapeHTML(p.descricao)}</p><strong>${money(p.preco)}</strong><p><button data-add="${escapeHTML(p.id)}" ${p.estoque<1?'disabled':''}>${p.estoque<1?'Indisponível':'Adicionar'}</button></p></article>`).join(''):'<div class="empty">Nossas novidades chegam em breve.</div>';renderCart();}catch(e){catalog.textContent=e.message;}}
document.addEventListener('click',async e=>{const add=e.target.closest('[data-add]'),remove=e.target.closest('[data-remove]');if(add){add.disabled=true;try{await loja.addToCart(add.dataset.add);await renderCart();result.textContent='Adicionado às suas escolhas.';}catch(err){result.textContent=err.message;}finally{add.disabled=false;}}if(remove){loja.removeFromCart(remove.dataset.remove);renderCart();}});
document.getElementById('checkout').addEventListener('click',async e=>{e.target.disabled=true;try{const order=await loja.simulate(document.getElementById('method').value);result.textContent=`Demonstração concluída: ${order.code} · ${money(order.total)}. Sem cobrança ou envio.`;await renderCart();}catch(err){result.textContent=err.message;e.target.disabled=false;}});
load();
